version: 0.2
env:
  variables:
    S3_BUCKET: my-packages-bucket
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm test
      - npm build

  post_build:
    commands:
      - cd ../outputDirectory
      - zip -r myBuild.zip .
      - aws s3 cp myBuild.zip s3://${S3_BUCKET}/myBuild.zip
