version: 0.2
env:
  variables:
    S3_BUCKET: richnet-website
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm build
  post_build:
    commands:
      - pwd
      - zip -r myBuild.zip .
      - aws s3 cp myBuild.zip s3://${S3_BUCKET}/myBuild.zip
